import type { AppProps } from "next/app";
import Head from "next/head";
import Navbar from "../components/utils/Navbar";
import "../styles/globals.css";

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main>
                <Component {...pageProps} />
            </main>
        </>
    );
}

export default MyApp;
